version: "3"
services:
  aws-currency-exchange-service-prometheus:
    image: sapphire03/aws-currency-exchange-service-prometheus:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
#  alertmanager:
#    image: prom/alertmanager:latest
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus